# Generated by Django 3.0.8 on 2020-07-15 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='proce',
            new_name='price',
        ),
    ]
