# Generated by Django 3.0.8 on 2020-07-15 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
