# Generated by Django 3.0.8 on 2020-07-16 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_property_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
