# Generated by Django 3.0.4 on 2020-07-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20200719_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], max_length=20),
        ),
    ]
