# Generated by Django 3.0.4 on 2020-07-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20200719_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('notes', models.TextField()),
            ],
            options={
                'verbose_name': 'Reserve',
                'verbose_name_plural': 'Reserves',
            },
        ),
    ]
