# Generated by Django 3.0.4 on 2020-07-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
